[colors.bright]
black = "0x696969"
blue = "0x007FFF"
cyan = "0x00CCCC"
green = "0x03C03C"
magenta = "0xFF1493"
red = "0xFF2400"
white = "0xFFFAFA"
yellow = "0xFDFF00"

[colors.normal]
black = "0x10100E"
blue = "0x0087BD"
cyan = "0x20B2AA"
green = "0x009F6B"
magenta = "0x9A4EAE"
red = "0xC40233"
white = "0xC6C6C4"
yellow = "0xFFD700"

[colors.primary]
background = "0x10100E"
foreground = "0xC6C6C4"

[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 2
y = 1

[window.padding]
x = 2

[keyboard]
bindings = [
{ key = "Left",     mods = "Alt",     chars = "\u001BB"                       }, # Skip word left
{ key = "Right",    mods = "Alt",     chars = "\u001BF"                       }, # Skip word right
{ key = "Left",     mods = "Command", chars = "\u001BOH", mode = "AppCursor"  }, # Home
{ key = "Right",    mods = "Command", chars = "\u001BOF", mode = "AppCursor"  }, # End
{ key = "Back",     mods = "Command", chars = "\u0015"                        }, # Delete line
{ key = "Back",     mods = "Alt",     chars = "\u001b\u007f"                    }, # Delete word
]
